### ISSUE TITLE
Middleware: Kreirati algoritam za nasumičan odabir id-a iz biljne vrste iz JSON formata zapisa u kojem se nalazi popis svih biljnih vrsta.

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa-2022#12]

**Comment by eshaton** [comment]
Issue #12 Middleware - riješen

**Comment by vdavid033** [comment]
@pjuric, @nino9333 - napraviti review

**Comment by nino9333** [comment]
Middleware - algoritam za nasumičan odabir id-a iz biljne vrste iz JSON formata zapisa u kojem se nalazi popis svih biljnih vrsta - radi
<img width="540" alt="review" src="https://user-images.githubusercontent.com/60181404/162031216-e18079c0-1b52-403c-b15f-ab2eff0c27f6.PNG">
