### ISSUE TITLE
Middleware: Kreirati algoritam za prikaz nekoliko nasumičnih biljnih porodica iz JSON formata zapisa u kojem se nalazi popis svih biljnih porodica.

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa-2022#13]

**Comment by vdavid033** [comment]
@vdavid033, @GordanaGL - napraviti review

**Comment by vdavid033** [comment]
Prijedlog: 
Dohvaćanje svih biljnih vrsta (plant_species) - možda nije potrebno dohvatiti sve
Dohvaćanje svih rodova za određenu biljnu vrstu (genus) - prosljeđuje se id biljne vrste. Biljna vrsta pripada jednom rodu. Je li potrebno uopće dohvaćanje biljnog roda?
Dohvaćanje svih botaničkih porodica (botanical_family) - u redu
Kako ćemo znati koja je botanička porodica odabrane biljne vrste?
Odabiranje 4 biljnih porodica nasumičnim izborom - u redu
Ispis nasumično odabranih biljnih porodica - u redu

**Comment by GordanaGL** [comment]
Kako ćemo znati koja je botanička porodica odabrane biljne vrste? - tako da se odabranoj biljnoj vrsti dodijeli i ID botaničke porodice kojoj pripada.
