### ISSUE TITLE
Middleware: Kreirati algoritam za prikaz jedne biljne porodice koja pripada zadanoj biljnoj vrsti (id) iz JSON formata zapisa u kojem se nalazi popis biljnih vrsta i biljnih porodica.

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa-2022#14]

**Comment by vdavid033** [comment]
#21 Dohvat bot.porodice za jednu biljnu vrstu - API
#13 Algoritam za prikaz nekoliko bot.porodica (vezuje se na API #19) - prikazuje jedan točan odgovor i nekoliko proizvoljnih.

Student odabire odgovor i provjerava se ako je id odabrane bot.porodice identičan s id bot.porodice iz #21

**Comment by nino9333** [comment]
Algoritam za prikaz jedne biljne porodice koja pripada zadanoj biljnoj vrsti (id) iz JSON formata zapisa u kojem se nalazi popis biljnih vrsta i biljnih porodica - radi
<img width="486" alt="Snimka zaslona 2022-04-11 225452" src="https://user-images.githubusercontent.com/60181404/162830559-3ee0541c-1815-4365-b599-90fb09018972.png">

**Comment by martinasuman** [comment]
algoritam za provjeru točnog odgovora radi-prilog
![algoritam](https://user-images.githubusercontent.com/102186252/162831788-8301e88e-5201-4412-a2ff-19c016e246a7.JPG)

Dodatak za algoritam 
1.) korisnik klikne na jedan odgovor(botanicku porodicu) -dohvat ID odabrane botanicke porodice
2.) ID odabrane botanicke porodice  na koju je korisnik kliknuo se usporeduje se ID botanicke porodice biljne vrste na koju se odnosi pitanje
3.) ako je ID odabrane = ID na koju se odnosi pitanje-> korisniku se šalje informacija da je odgovor tocan, inace netocan

**Comment by pjuric** [comment]
![moguci problem sa upitom](https://user-images.githubusercontent.com/72385188/163172116-9aa1b177-35d8-4c6a-a556-02c841a58d5d.JPG)

Mogući problem sa upitom? Iako u plant_species postoji entitet sa id = 4, nakon pokrenutog query-ja se ništa ne vraća (prikaz na slici iznad).

**Comment by martinasuman** [comment]
> ![moguci problem sa upitom](https://user-images.githubusercontent.com/72385188/163172116-9aa1b177-35d8-4c6a-a556-02c841a58d5d.JPG)
> 
> BotanicalFamilyFromPlantSpecies.js Mogući problem sa upitom? Iako u plant_species postoji entitet sa id = 4, nakon pokrenutog query-ja se ništa ne vraća (prikaz na slici iznad). Odabirom id = 1 ili 2 se vraćaju podaci (slika ispod).
> 
> ![provjera upita](https://user-images.githubusercontent.com/72385188/163172595-4363f936-ce62-4e93-8793-09fcdd878f5a.JPG)

zato što u bazi ne postoji botanical_family id=1

**Comment by pjuric** [comment]
> 

moja greska onda... gledao sam samo ovaj zadnji dio "where plant_species.id=?"
