### ISSUE TITLE
Frontend: Na temelju mockup prozora naći i predložiti grafičke komponente iz Quasar.js razvojnog okvira (pogledati dokumentaciju)

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa-2022#17]

**Comment by FilipVasiljevic** [comment]
Postavljeno u 1_korsinicku_pricu

**Comment by FilipVasiljevic** [comment]
[Rijesenje_na_temelju_mockupa-Vasiljevic.docx](https://github.com/vdavid033/iooa-2022/files/8424808/Rijesenje_na_temelju_mockupa-Vasiljevic.docx)

**Comment by vdavid033** [comment]
Konvertirati u md datoteku

**Comment by FilipVasiljevic** [comment]
[Rijesenje_na_temelju_mockupa.md](https://github.com/vdavid033/iooa-2022/files/8428472/Rijesenje_na_temelju_mockupa.md)
![Rijesenje_na_temelju_mockupa_slika](https://user-images.githubusercontent.com/101420754/162013953-225b2732-f1b1-4c12-a99d-b309bfbd2327.png)

**Comment by vdavid033** [comment]
@eshaton, @mvodvarka - napraviti review

**Comment by mvodvarka** [comment]
Predložio bih sljedeći koncept mock-up prozora (tj. više kao neki prijedlog za dizajn sučelja samog kviza):

[https://quasar.dev/layout/layout#qlayout-api](url)

- u pitanju je korištenje API-ja pod nazivom **QLayout API** 

QLayout je komponenta dizajnirana za upravljanje cijelim prozorima i ispunjavanje sadržaja stranice elementima kao što je npr. navigacijska traka. Više stranica može koristiti isti QLayout, tako da se isti kod može koristiti više puta. 

###Layout ###Builder

'Layout Builder' može koristiti komponente koje nisu već umetnute u quasar.config.js paket, tako da će Vam najvjerojatnije  trebati sljedeće komponente: 

1. QLayout
2. QHeader
3. QToolbar
4. QToolbarTitle
5. QBtn
6. QAvatar
7. QTabs
8. QRouteTab
9. QDrawer
10. QPageContainer
11. QFooter

Link za Layout Builder: [https://quasar.dev/layout-builder](url)

Prema zadanim postavkama, QLayout upravlja cijelim prozorom. Međutim, QLayout također možete koristiti kao spremnik (sa određenom visinom i širinom) kako biste ga izolirali negdje na svojim stranicama. 

Link za primjer QLayout spremnika: [https://quasar.dev/layout/layout#example--containerized-qlayout](url)

**Comment by FilipVasiljevic** [comment]
Na temelju mockupa od @eshaton saljem sliku frontenda. Korištene komponente su:
-button group (https://quasar.dev/vue-components/button-group#introduction)
-button (https://quasar.dev/vue-components/button#introduction)
-img (https://quasar.dev/vue-components/img#introduction)
-radio (https://quasar.dev/vue-components/radio#introduction


![Prijedlog na temelju mockupa](https://user-images.githubusercontent.com/101420754/162258615-009a995c-e0bd-4ba1-8cd2-12723a84010c.png)
)

**Comment by FilipVasiljevic** [comment]
Kod za sliku gore je u development grani u frontendu pod IndexPage.vue
