### ISSUE TITLE
Backend: Izraditi web servis (API) za dohvat svih biljnih vrsta

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa-2022#18]

**Comment by vdavid033** [comment]
@lukababic19, @bGlav, @Veleri0  - napraviti review

**Comment by bGlav** [comment]
Nemože se odraditi review iz razloga što nedostaje /db.config.js i zato nije moguće pokrenuti server.

**Comment by eshaton** [comment]
Kod je ispravan.
![image](https://user-images.githubusercontent.com/15856394/162898048-ae1842e4-9f84-400b-8452-2cec714000c1.png)
