### ISSUE TITLE
Backend: Izraditi web servis (API) za dohvat svih biljnih porodica

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa-2022#19]

**Comment by ivanaab** [comment]
API za dohvat svih biljnih porodica je izrađen u datoteci index.js 2_korisnicka_prica

**Comment by tonko555** [comment]
API za dohvat svih biljnih porodica radi

**Comment by vdavid033** [comment]
Postavite ispis u datoteku

**Comment by tonko555** [comment]
![278234707_1673449533004602_8428736686028370759_n](https://user-images.githubusercontent.com/101736746/163214999-fda553cb-3955-427c-9c93-3f19a558134f.png)
