### ISSUE TITLE
Backend: Izraditi web servis (API) za dohvat biljne porodice za jednu biljnu vrstu

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa-2022#21]

**Comment by msiladjev** [comment]
dohvat biljne porodice za jednu biljnu vrstu je izrađeno u datoteci index.js (2_korisnicka_prica)

**Comment by vdavid033** [comment]
@tkrznaric, @FilipVasiljevic - napraviti review

**Comment by msiladjev** [comment]
dohvat biljne porodice za jednu biljnu vrstu je izrađeno u datoteci index.js (2_korisnicka_prica)

**Comment by FilipVasiljevic** [comment]
Kod za dohvat biljne vrste (plant_species) radi kako treba
![Plant_species](https://user-images.githubusercontent.com/101420754/162027200-e6c72a4a-6356-45b6-8222-435d0d877af1.png)
.
