### ISSUE TITLE
Backend: Izraditi web servis (API) za dohvat svih biljnih vrsta za jednu biljnu porodicu

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa-2022#23]

**Comment by vdavid033** [comment]
@msiladjev, @ivanaab, @sbrozan  - napraviti review

**Comment by msiladjev** [comment]
[
![image](https://user-images.githubusercontent.com/101736711/162030489-e3e2e5c1-52c7-49e0-bb28-9b4d05ecd624.png)
](url)

Kod za dohvat svih biljnih vrsta za jednu biljnu porodicu - radi
Pristupanje: http://localhost:3000/plant_species_by_bf/21
