### ISSUE TITLE
Početni prozor

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa-2022#28]
**Početni prozor - definiranje layouta (slika u pozadini, prijedlog boja, naslov, gumb za startanje kviza)**

Ovdje dodajte screenshot i poveznicu na izrađene datoteke -> ne sve, samo one koje ste izmijenili.

**Comment by tkrznaric** [comment]
issue #28
![Snimka zaslona (289)](https://user-images.githubusercontent.com/101366668/164005274-b80b2873-8430-4685-9508-83b05b2d23ed.png)
[TamaraPrijedlog.zip](https://github.com/vdavid033/iooa-2022/files/8512999/TamaraPrijedlog.zip)

**Comment by lukababic19** [comment]
![pocetnaslika](https://user-images.githubusercontent.com/101427586/164249323-5e8e4c83-a332-43db-a78a-911f744505bc.png)
[pocetni_zaslon.zip](https://github.com/vdavid033/iooa-2022/files/8522173/pocetni_zaslon.zip)

**Comment by sbrozan** [comment]
![Capture](https://user-images.githubusercontent.com/101737307/164275713-ed4dbd7c-626a-4054-8c79-a54333dfca29.PNG)

**Comment by vdavid033** [comment]
Početni prozor:
pages/IndexPage.vue
layouts/MainLayout.vue

@tkrznaric, @lukababic19 , @sbrozan - ažurirati zajedno
