### ISSUE TITLE
Prikaz nasumično odabranih botaničkih porodica

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa-2022#32]
**Prikaz više nasumično odabranih botaničkih porodica - dohvatiti i prikazati botaničke porodice, napraviti Quasar komponente QButton i RadioButton.**

Ovdje dodajte screenshot i poveznicu na izrađene datoteke -> ne sve, samo one koje ste izmijenili.

**Comment by eshaton** [comment]
![image](https://user-images.githubusercontent.com/15856394/164161777-cf3706fd-98c6-4735-8d80-4fd0995b53c0.png)
Link na .vue datoteku:
https://github.com/vdavid033/iooa-2022/blob/eshaton/frontend/Isuue%20%2332_Prikaz%20nasumicno%20odabranih%20botanickih%20porodica.png

**Comment by vdavid033** [comment]
Radi se na KvizPage.vue
- odraditi nakon što se doda pitanje i odgovori

**Comment by eshaton** [comment]
Napravljene izmjene, prema uputama napravljena KvizPage.vue, dodana ruta na nju sa glavne stranice i funkcija rutiranja na KvizPage sa gumba na glavnoj stranici. Ima još posla ali nazire se kompletno rješenje.
https://github.com/vdavid033/iooa-2022/blob/eshaton/frontend/quasar-project/src/pages/KvizPage.vue

**Comment by vdavid033** [comment]
@eshaton Izvrsno! Možete preimenovati datoteku u KvizPage1.vue i dodati je u routes.js. Sve skupa prebacite na development granu.

**Comment by eshaton** [comment]
KvizPage1.vue datoteka postavljena u development granu 
- kod koji uzima nasumične vrijednosti iz datoteke botanical_family.json, izvlači hrvatska imena i poslužuje ih u "label" properti option group liste. Postupak se ponavlja pritiskom da gump sljedeće pitanje...TODO: razraditi metodu da svaki od dva ponuđena odgovora uvijek bude različit (napraviti provjeru svih "label"-a prije ispisivanja prijedloga prijedloga i napraviti metodu koja izvlači točan odgovor. Sve to skupa spojiti sa KvizPage.vue datotekom.

**Comment by vdavid033** [comment]
Spojiti nasumične odgovore s KvizPage.vue

**Comment by eshaton** [comment]
Riješeno. Ostalo samo iščupati točan odgovor prema generiranom pitanju. Napravljena provjera od dupliciranog odgovora i nasumičan raspored odgovora. Postavljeno mjesto za ispis točnog odgovora koje se mijenja random prilikom generiranja svakog pitanja.
https://github.com/vdavid033/iooa-2022/blob/eshaton/frontend/quasar-project/src/pages/KvizPage.vue
