### ISSUE TITLE
Provjera i prikaz točnog odgovora

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa-2022#33]
**Provjera i prikaz točnog odgovora preko:**  
**1. iskočnog prozora - @Bojan159 
2. kvačice ili x - @dmedurant  
3. boje radio gumba - @FilipVasiljevic**

Ovdje dodajte screenshot i poveznicu na izrađene datoteke -> ne sve, samo one koje ste izmijenili.

**Comment by FilipVasiljevic** [comment]
Boje radio gumba treba doraditi jer se ne mogu otkriti kako da promjene boju nakon što kliknem prihvati odgovor

https://user-images.githubusercontent.com/101420754/164191586-89f0c775-05c3-44bb-95a7-5fd1841eef34.mp4

**Comment by FilipVasiljevic** [comment]
Boje radio gumba treba doraditi jer ne uspijevam napraviti da promjene boju nakon pritiska gumba prihvati odgovor. 

https://user-images.githubusercontent.com/101420754/164193721-9a579f16-5991-4402-9f64-bb0e754c9363.mp4

**Comment by vdavid033** [comment]
Ažurirati KvizPage.vue na development grani

**Comment by FilipVasiljevic** [comment]
https://github.com/vdavid033/iooa-2022/blob/development/frontend/quasar-project/src/pages/IndexPage.vue

Postavljena stranica IndexPage.vue

**Comment by FilipVasiljevic** [comment]
https://github.com/vdavid033/iooa-2022/blob/development/frontend/quasar-project/src/pages/KvizPage.vue

Stvorena KvizPage.vue na development grani
