### ISSUE TITLE
Gumb za povratak

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa-2022#34]
**Gumb za povratak na početnu stranicu (početak kviza)**

Ovdje dodajte screenshot i poveznicu na izrađene datoteke -> ne sve, samo one koje ste izmijenili.

**Comment by nino9333** [comment]
Primjeri za home button
<img width="883" alt="Primjer home button" src="https://user-images.githubusercontent.com/60181404/163675716-aac4ae81-9f6c-45eb-9776-1c8dd917e4be.PNG">

**Comment by nino9333** [comment]
https://github.com/vdavid033/iooa-2022/blob/nino9333/frontend/QBtn.vue
Primjeri više button-a za home, link za trenutni home: http://agro.veleri.hr/biljne-vrste/ , kasnije izmjenimo kada imamo home za kviz

**Comment by pjuric** [comment]
Izrađena je komponenta sa primjerima gumbova za povratak na početnu stranicu, dostupno na poveznici: https://github.com/vdavid033/iooa-2022/blob/pjuric/frontend/quasar-project/src/components/BackHomeButton.vue. 

Izgled primjeraka za gumb je dostupan na slici:
![gumbi_quasar](https://user-images.githubusercontent.com/72385188/163831585-c4c0e179-3942-491f-8b0b-a0d636c58df0.png)

Komponenta je smještena u "src/components" i moguće ju je importati u bilo kojoj stranici ili komponenti. Gumbu je moguće jednostavno promijeniti boju jer je odabrana "custom color" komponenta gumba te ju je na taj način moguće lakše prilagoditi glavnoj temi (dizajnu) aplikacije (mijenjanjem "color" i "background" atributa). Isto tako, poveznica gumba je za sada postavljena na "/", a moguće ju je promijeniti na "props -> link" unutar programskog djela komponente (script), kao što je i moguće promijeniti tekst unutar gumba ("props -> caption"). Nakon što se odabere neki od gumbova, ostale je dovoljno samo izbrisati iz koda ili zakomentirati.

**Comment by pjuric** [comment]
Prijedlog: možda bi bilo dobro da se "frontend/quasar-project" folder postavi kao root direktorij za cjeli frontend, a sve datoteke izvan "quasar-project" stave u jedan poseban direktorij unutar "quasar-project".

**Comment by vdavid033** [comment]
Dodati gumb za povratak u KvizPage.vue, s povratkom na početnu stranicu.
Radi se na development grani

**Comment by vdavid033** [comment]
Napraviti i gumb za iduće pitanje

**Comment by nino9333** [comment]
Dodan je button za početnu straniu u KvizPage.vue i MainLayout.vue 
MainLayout.vue - (https://github.com/vdavid033/iooa-2022/blob/development/frontend/quasar-project/src/layouts/MainLayout.vue) - linija koda od 13-18
KvizPage.vue - (https://github.com/vdavid033/iooa-2022/blob/development/frontend/quasar-project/src/pages/KvizPage.vue) - linija koda od 3-9

**Comment by nino9333** [comment]
Trenutni prikaz stranice (Button desno gore u kutu)
<img width="1277" alt="Kviz" src="https://user-images.githubusercontent.com/60181404/165028038-a1142883-683a-41ac-87eb-4cd287c907aa.PNG">

**Comment by pjuric** [comment]
Par izmjena u https://github.com/vdavid033/iooa-2022/blob/development/frontend/quasar-project/src/pages/KvizPage.vue.
Uklonjen gumb sa KvizPage.vue koji se već nalazi u glavnom layout-u (https://github.com/vdavid033/iooa-2022/blob/development/frontend/quasar-project/src/layouts/MainLayout.vue) što znači da se pojavljuje 2 puta  (jedan je bio skriven iza headera pa se nije vidio). Pošto je element ispod njega bio postavljen na "absolute", došlo je do ispreplitanja sa header elementom iz layout-a pa je bilo potrebno dodatno stilizirati elemente. 

![button delete and style](https://user-images.githubusercontent.com/72385188/165181429-1b65acda-d5b9-4d23-b9c3-4fea0b3fa610.JPG)

**Comment by vdavid033** [comment]
Gumb "Početna stranica" vraća na "Započni kviz" - osnovnu stranicu.
Dodati gumb za odlazak na aplikaciju.
