### ISSUE TITLE
Dohvat biljnih vrsta u json formatu s API-ja

### ISSUE THREAD

**Issue by vdavid033** [vdavid033/iooa-2022#36]
Kreirati novu datoteku koja će dohvatiti i spremiti biljne vrste u json format. 
Testirati dohvat preko axios-a.

**Comment by tkrznaric** [comment]
Zadatak #36 je završen.U backend  u index.js smo dodali cons cors=require ('cors');
                                                                             app.use(cors({
                                                                             origin:'*'
                                                                              }));
U frontendu je kreirana nova datoteka KvizPage2.vue i napravljena je putanja(path) za nju ,no prije toga je bilo potrebno instalirati axios.
