### ISSUE TITLE
Testiranje 1 - Kviz4- ne radi popup za prikaz točnog odgovora na zadnje pitanje

### ISSUE THREAD

**Issue by martinasuman** [vdavid033/iooa-2022#48]
Klikom na odgovor na 10. pitanje, onemogućen je klik na Prikaz odgovora, samim time je i prikaz statistike krivi, prikazuje se statistika za 9 pitanja umjesto za 10
![10pitanje](https://user-images.githubusercontent.com/102186252/170083331-a32a3833-9581-4de3-9880-821a140cd91a.JPG)

**Comment by eshaton** [comment]
Kolega @Bojan159 i ja riješili smo problem brojanja pitanja i prikaz zbrajanja rezultata.

**Comment by vdavid033** [comment]
![bug](https://user-images.githubusercontent.com/48751193/171594736-54e916c4-4f6f-4ef7-8b46-0e8b28fc239e.png)

Meni se javlja ovaj rezultat.

**Comment by vdavid033** [comment]
@martinasuman @tkrznaric @eshaton @Bojan159 - provjerite dobivate li ovakve rezultate?

**Comment by Bojan159** [comment]
![Screenshot 2022-06-02 120436](https://user-images.githubusercontent.com/101737037/171606825-f0c4f0cf-5505-44a5-b3d9-b05b1176e234.jpg)

Meni radi sve normalno

**Comment by vdavid033** [comment]
Provjerit ću. Moguće da nisam preuzela sve datoteke s development verzije. 
I pitanje @Bojan159 ... na kojoj verziji Node.js-a radite?

Neka i ostali isto provjere rezultate

**Comment by Bojan159** [comment]
Node.js v16.14.2
Quasar 1.3.2

**Comment by vdavid033** [comment]
Dakle, zadnje pitanje se sad odgovara klikom na Prihvati i završi? 

Možete li vratiti da se i zadnje pitanje odgovara s Prihvati odgovor?
Nakon toga da se onemogući klik na Prihvati i završi, a pojavi gumb Prihvati i završi - dakle kao što je prije radilo. 
Klikom na Prihvati i završi se ispisuje rezultat. U pozadini se ne bi trebao raditi refresh na novo pitanje.

Ovo bi trebalo tako napraviti radi konzistentnosti u radu korisnika s aplikacijom.

**Comment by vdavid033** [comment]
![bug1](https://user-images.githubusercontent.com/48751193/171636028-a330c598-6bac-4fb5-9f1b-d34a64193fa6.png)

Ovo je radilo problem?

**Comment by eshaton** [comment]
Var se nije inkrementirala na prvi klik, a svi sljedeci klikovi je  podizu
za 1 i odmah nakon postepeno spustaju na inicijalnu vrijednost. U svakom
slucaju cudno

čet, 2. lip 2022. 15:08 vdavid033 ***@***.***> je napisao:

**Comment by tkrznaric** [comment]
![Snimka zaslona (338)](https://user-images.githubusercontent.com/101366668/171819484-29f1d71e-f517-4ce8-aeb6-1bf1f3b13eae.png)
 @vdavid033  napravila sam pull sa development grane , učitava se 10 pitanje , klikne se na odgovor ali ne izbacuje mi brojač pitanja odnosno broj točnih i netočnih odgovora. 11 pitanje se ne učitava.
